library pisey_ui_kits;

import 'package:flutter/material.dart';
// import 'package:scroll_app_bar/scroll_app_bar.dart';
// import 'package:scroll_bottom_navigation_bar/scroll_bottom_navigation_bar.dart';
import 'package:eva_icons_flutter/eva_icons_flutter.dart';
import 'package:flutter/rendering.dart';
import 'package:image_picker/image_picker.dart';
import 'package:dots_indicator/dots_indicator.dart';
// import 'package:md2_tab_indicator/md2_tab_indicator.dart';
// import 'package:flutter_image_compress/flutter_image_compress.dart';
import 'package:intl/intl.dart';
import 'dart:io';

part 'src/utils/color_dark.dart';
part 'src/utils/colors.dart';
part 'src/utils/fonts.dart';
// part 'src/utils/page_transformer.dart';
part 'src/utils/text_string.dart';
part 'src/widgets/expansion_list.dart';
part 'src/utils/text_styles.dart';
part 'src/utils/util_ui.dart';
part 'src/widgets/bottom_nav.dart';
part 'src/widgets/button.dart';
part 'src/widgets/dropdown_list.dart';
part 'src/widgets/grid_view.dart';
part 'src/widgets/list_tile.dart';
part 'src/widgets/list_view.dart';
part 'src/widgets/page_view.dart';
part 'src/widgets/tab_bar.dart';
part 'src/widgets/tab_model.dart';
part 'src/widgets/text_field.dart';
part 'service/get_date.dart';
part 'service/next_screen.dart';
part 'service/pick_image.dart';
